language: bash

services:
  - docker
  - mysql

before_install:
  - docker pull tp33/django
  - docker pull mysql:5.7.23
  - mkdir db
  - docker run --name mysql -d -e MYSQL_ROOT_PASSWORD='$3cureUS' -v db:/var/lib/mysql mysql:5.7.23
  - sleep 30
  - docker run -it --name mysql-cmdline --link mysql:db mysql:5.7.23 mysql -uroot -p'$3cureUS' -h db -e "create user 'www'@'%' identified by '\$3cureUS'; create database cs4501 character set utf8; grant all on *.* to 'www'@'%';"
before_script: 
  - docker start mysql
  - sleep 5
  - docker-compose up -d 
  - docker network connect cs4260_isa_backend mysql
  - docker-compose stop 
  - docker ps -a
  - sleep 3
  - docker-compose up -d
  - sleep 10
  - docker ps -a

script: 
  - docker exec -it models bash -c "cd isa; python manage.py test"

after_script:
  - docker-compose stop
  - docker-compose down