language: bash

services: 
docker

# before_install contains mostly project 1 stuff
before_install:
- docker pull tp33/django
- docker pull mysql:latest
- mkdir ~/cs4501/db
- docker run --name mysql -d -e MYSQL_ROOT_PASSWORD='$3cureUS' -v ~/cs4501/db:/var/lib/mysql  mysql:latest
- sleep 20
- docker run -it --name mysql-cmdline --link mysql:db mysql:latest mysql -uroot -p'$3cureUS' -h db -e "create user 'www'@'%' identified by '\$3cureUS'; create database cs4501 character set utf8; grant all on cs4501.* to 'www'@'%'; grant all on test_cs4501.* to 'www'@'%';"

script:
- docker-compose up -d --build
- sleep 200

after_script:
- docker-compose stop
- docker-compose down