version: "3"
services:

  models:
    image: tp33/django
    external_links:
      - mysql:db
    volumes:
      - /app:/app
    ports:
      - "8001:8000"
    networks:
      - backend
    command: bash -c "mod_wsgi-express start-server --working-directory C:/Users/Karim/cs4501/ --reload-on-changes /app/cs4260_ISA/isa/isa/wsgi.py"

networks:
  backend: