version: "3"
services:

  models:
    image: tp33/django
    external_links:
      - mysql:db
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    networks:
      - backend
    command: bash -c "python ./isa/manage.py migrate && python ./isa/manage.py loaddata ./isa/db.json && mod_wsgi-express start-server --working-directory ./isa --reload-on-changes ./isa/isa/wsgi.py"

networks:
  backend:
    
