# Generated by Django 2.2.4 on 2019-09-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jersey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='shirt_size',
            field=models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Double Extra Large')], max_length=3),
        ),
    ]
