# Generated by Django 2.2.4 on 2019-10-07 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jersey', '0003_auto_20190920_2040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jersey',
            options={'ordering': ('-id',)},
        ),
    ]
