# Generated by Django 2.2.4 on 2019-10-07 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jersey', '0004_auto_20191007_1708'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jersey',
            options={},
        ),
    ]
