# Generated by Django 2.2.4 on 2019-10-18 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jersey', '0006_auto_20191010_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='jersey',
            name='user_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='jersey.User'),
            preserve_default=False,
        ),
    ]
