# Generated by Django 2.2.4 on 2019-10-19 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jersey', '0007_jersey_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=32),
        ),
    ]
