# Generated by Django 2.2.4 on 2019-10-21 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jersey', '0009_auto_20191019_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jersey',
            name='number',
            field=models.IntegerField(),
        ),
    ]
